server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/ems_dr
spring.datasource.username=dr
spring.datasource.password=dr123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher