server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/ems_prod?useSSL=true&serverTimezone=UTC
spring.datasource.username=prod
spring.datasource.password=prod123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=/opt/uploads
spring.mvc.pathmatch.matching-strategy=ant_path_matcher